---

version: '3'
services:
  web:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - '..:/app'
    entrypoint: ''
  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: hello_world
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret
    volumes:
      - ../../.mysql/hello-world:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
