---

version: '3'
services:
  web:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - '..:/app'
    entrypoint: ''
  db:
    image: 'mysql'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
